name: boostrap_bloc_builder_plugin
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.2 <3.0.0'

dependencies:
  analyzer_plugin: ^0.2.1



